version: '3.8'
services:
  postgres:
    image: postgres:latest
    networks:
      - greenbowl_network
    volumes:
      - ./db/data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"
    environment:
      - TZ=Asia/Seoul
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgresuser
      - POSTGRES_DB=greenbowl

  recommendation-adapters:
    image: greenbowl-recommendation-adapters:1.0.0
    networks:
      - greenbowl_network
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/greenbowl
      - SPRING_DATASOURCE_USERNAME=postgresuser
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create

  fridge-adapters:
    image: greenbowl-fridge-adapters:1.0.0
    networks:
      - greenbowl_network
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/greenbowl
      - SPRING_DATASOURCE_USERNAME=postgresuser
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create

  recipe-adapters:
    image: greenbowl-recipe-adapters:1.0.0
    networks:
      - greenbowl_network
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/greenbowl
      - SPRING_DATASOURCE_USERNAME=postgresuser
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create

networks:
  greenbowl_network:
    driver: bridge
