-- 테이블 생성
create table default_category_item
(
    id              bigserial
        primary key,
    created_at      timestamp             not null,
    modified_at     timestamp,
    delete_yn       boolean default false not null,
    category        integer,
    category_detail varchar(255)
);

-- 카테고리 1: 채소
INSERT INTO default_category_item (category, category_detail, created_at, modified_at) VALUES
                                               (1, '가지', now(), now()),
                                               (1, '감자', now(), now()),
                                               (1, '고구마', now(), now()),
                                               (1, '고추', now(), now()),
                                               (1, '꺳잎', now(), now()),
                                               (1, '나물', now(), now()),
                                               (1, '당근', now(), now()),
                                               (1, '더덕', now(), now()),
                                               (1, '두부', now(), now()),
                                               (1, '마', now(), now()),
                                               (1, '마늘', now(), now()),
                                               (1, '무', now(), now()),
                                               (1, '배추', now(), now()),
                                               (1, '버섯', now(), now()),
                                               (1, '부추', now(), now()),
                                               (1, '브로콜리', now(), now()),
                                               (1, '상추', now(), now()),
                                               (1, '샐러드', now(), now()),
                                               (1, '생강', now(), now()),
                                               (1, '시금치', now(), now()),
                                               (1, '아스파라거스', now(), now()),
                                               (1, '양배추', now(), now()),
                                               (1, '양상추', now(), now()),
                                               (1, '양파', now(), now()),
                                               (1, '연근', now(), now()),
                                               (1, '오이', now(), now()),
                                               (1, '옥수수', now(), now()),
                                               (1, '우엉', now(), now()),
                                               (1, '인삼', now(), now()),
                                               (1, '콩나물', now(), now()),
                                               (1, '파', now(), now()),
                                               (1, '파프리카', now(), now()),
                                               (1, '피망', now(), now()),
                                               (1, '허브류', now(), now()),
                                               (1, '호박', now(), now());

-- 카테고리 2: 과일
INSERT INTO default_category_item (category, category_detail, created_at, modified_at) VALUES
                                               (2, '감', now(), now()),
                                               (2, '귤', now(), now()),
                                               (2, '딸기', now(), now()),
                                               (2, '레몬', now(), now()),
                                               (2, '망고', now(), now()),
                                               (2, '멜론', now(), now()),
                                               (2, '바나나', now(), now()),
                                               (2, '배', now(), now()),
                                               (2, '복숭아', now(), now()),
                                               (2, '블루베리', now(), now()),
                                               (2, '사과', now(), now()),
                                               (2, '석류', now(), now()),
                                               (2, '수박', now(), now()),
                                               (2, '아보카도', now(), now()),
                                               (2, '오렌지', now(), now()),
                                               (2, '자두', now(), now()),
                                               (2, '자몽', now(), now()),
                                               (2, '참외', now(), now()),
                                               (2, '체리', now(), now()),
                                               (2, '키위', now(), now()),
                                               (2, '토마토', now(), now()),
                                               (2, '파인애플', now(), now()),
                                               (2, '포도', now(), now());

-- 카테고리 3: 육류
INSERT INTO default_category_item (category, category_detail, created_at, modified_at) VALUES
                                               (3, '계란',now(), now()),
                                               (3, '국거리',now(), now()),
                                               (3, '닭가슴살',now(), now()),
                                               (3, '닭고기',now(), now()),
                                               (3, '돼지고기',now(), now()),
                                               (3, '뒷다리살',now(), now()),
                                               (3, '등심',now(), now()),
                                               (3, '메추리알',now(), now()),
                                               (3, '목살',now(), now()),
                                               (3, '삼겹살',now(), now()),
                                               (3, '소고기',now(), now()),
                                               (3, '소등심',now(), now()),
                                               (3, '소안심',now(), now()),
                                               (3, '소채끝',now(), now()),
                                               (3, '앞다리살',now(), now()),
                                               (3, '양고기',now(), now()),
                                               (3, '오리고기',now(), now());

-- 카테고리 4: 수산물
INSERT INTO default_category_item (category, category_detail, created_at, modified_at) VALUES
                                               (4, '갈치',now(), now()),
                                               (4, '게',now(), now()),
                                               (4, '고등어',now(), now()),
                                               (4, '굴',now(), now()),
                                               (4, '김',now(), now()),
                                               (4, '낙지',now(), now()),
                                               (4, '멸치',now(), now()),
                                               (4, '명란',now(), now()),
                                               (4, '문어',now(), now()),
                                               (4, '미역',now(), now()),
                                               (4, '새우',now(), now()),
                                               (4, '생선',now(), now()),
                                               (4, '오징어',now(), now()),
                                               (4, '전복',now(), now()),
                                               (4, '조개류',now(), now()),
                                               (4, '황태',now(), now());

-- 카테고리 5: 조미료
INSERT INTO default_category_item (category, category_detail, created_at, modified_at) VALUES
                                               (5, '간장', now(), now()),
                                               (5, '고추장', now(), now()),
                                               (5, '고춧가루', now(), now()),
                                               (5, '굴소스', now(), now()),
                                               (5, '깨', now(), now()),
                                               (5, '꿀', now(), now()),
                                               (5, '다진마늘', now(), now()),
                                               (5, '돈까스소스', now(), now()),
                                               (5, '된장', now(), now()),
                                               (5, '마요네즈', now(), now()),
                                               (5, '머스타드', now(), now()),
                                               (5, '물엿', now(), now()),
                                               (5, '발사믹드레싱', now(), now()),
                                               (5, '버터', now(), now()),
                                               (5, '새우젓', now(), now()),
                                               (5, '설탕', now(), now()),
                                               (5, '소금', now(), now()),
                                               (5, '시저드레싱', now(), now()),
                                               (5, '식용유', now(), now()),
                                               (5, '식초', now(), now()),
                                               (5, '쌈장', now(), now()),
                                               (5, '액젓', now(), now()),
                                               (5, '오리엔탈드레싱', now(), now()),
                                               (5, '올리브유', now(), now()),
                                               (5, '참기름', now(), now()),
                                               (5, '청국장', now(), now()),
                                               (5, '초고추장', now(), now()),
                                               (5, '칠리소스', now(), now()),
                                               (5, '케찹', now(), now()),
                                               (5, '후추', now(), now());

-- 카테고리 6: 가공/유제품
INSERT INTO default_category_item (category, category_detail, created_at, modified_at) VALUES
                                               (6, '국수', now(), now()),
                                               (6, '당면', now(), now()),
                                               (6, '두유', now(), now()),
                                               (6, '라면', now(), now()),
                                               (6, '마가린', now(), now()),
                                               (6, '버터', now(), now()),
                                               (6, '베이컨', now(), now()),
                                               (6, '생크림', now(), now()),
                                               (6, '어묵', now(), now()),
                                               (6, '연유', now(), now()),
                                               (6, '요거트', now(), now()),
                                               (6, '요구르트', now(), now()),
                                               (6, '우유', now(), now()),
                                               (6, '참치', now(), now()),
                                               (6, '치즈', now(), now()),
                                               (6, '파스타', now(), now()),
                                               (6, '햄', now(), now());

-- 카테고리 7: 견과/곡물
INSERT INTO default_category_item (category, category_detail, created_at, modified_at) VALUES
                                               (7, '귀리',now(), now()),
                                               (7, '도토리',now(), now()),
                                               (7, '땅콩',now(), now()),
                                               (7, '메밀',now(), now()),
                                               (7, '밀가루',now(), now()),
                                               (7, '밤',now(), now()),
                                               (7, '병아리콩',now(), now()),
                                               (7, '보리',now(), now()),
                                               (7, '부침가루',now(), now()),
                                               (7, '쌀',now(), now()),
                                               (7, '아몬드',now(), now()),
                                               (7, '오트밀',now(), now()),
                                               (7, '옥수수전분',now(), now()),
                                               (7, '잣',now(), now()),
                                               (7, '콩',now(), now()),
                                               (7, '퀴노아',now(), now()),
                                               (7, '튀김가루',now(), now()),
                                               (7, '팥',now(), now()),
                                               (7, '현미',now(), now()),
                                               (7, '호두',now(), now()),
                                               (7, '호밀',now(), now());
