apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-adapters
  namespace: greenbowl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recommendation-adapters
  template:
    metadata:
      labels:
        app: recommendation-adapters
    spec:
      containers:
        - name: recommendation-adapters
          image: hellmir/greenbowl-recommendation-adapters:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres.greenbowl.svc.cluster.local:5432/greenbowl"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgresuser"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
