apiVersion: v1
kind: Service
metadata:
  name: fridge-adapters
  namespace: greenbowl
spec:
  selector:
    app: fridge-adapters
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
