server:
  port: 8000
spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul
    serialization:
      fail-on-empty-beans: false
  cloud:
    gateway:
      routes:
        - id: fridge-adapters
          uri: lb://FRIDGE-ADAPTERS
          predicates:
            - Path=/category-items/**,/ingredients/**
eureka:
  client:
    enabled: false
logging:
  config: classpath:logback-spring.xml
