server:
  port: 8080
spring:
  application:
    name: recommendation-adapters
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${GREENBOWL_POSTGRES_URL}
    username: ${GREENBOWL_POSTGRES_USERNAME}
    password: ${GREENBOWL_POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
    show-sql: true
    database: postgresql
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul
    serialization:
      fail-on-empty-beans: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
logging:
  config: classpath:logback-spring.xml
frontend:
  url: ${GREENBOWL_FRONTEND_URL}
  vercel:
    url: ${GREENBOWL_FRONTEND_VERCEL_URL}
  swyg:
    url: ${GREENBOWL_FRONTEND_SWYG_URL}
llm:
  server:
    url: ${LLM_SERVER_API_URL}
    endpoint:
      streaming: ${LLM_SERVER_STREAMING_ENDPOINT}
      sse: /${LLM_SERVER_SSE_ENDPOINT}
  recipe:
    type: ${RECIPE_LLM_TYPE}
    template: ${RECIPE_LLM_TEMPLATE}
    secret-key: ${RECIPE_SECRET_KEY}
  menu:
    type: ${MENUS_LLM_TYPE}
    template: ${MENUS_LLM_TEMPLATE}
    secret-key: ${MENUS_SECRET_KEY}
  detailed-menu:
    type: ${DETAILED_MENU_LLM_TYPE}
    template: ${DETAILED_MENU_LLM_TEMPLATE}
    secret-key: ${DETAILED_MENU_SECRET_KEY}
